---
# tasks file for roles/claim

- name: Get information about running agent
  command: netdatacli aclk-state json
  register: agent_info

  #- set_fact: 
  #  is_online: "{{ agent_info.stdout | from_json | json_query('online') }}"

- set_fact: 
    is_claimed: "{{ agent_info.stdout | from_json | json_query('\"agent-claimed\"') }}"

- name: Claim the new node if is not claimed yet
  block:
    - name: Generate UUID
      command: uuidgen
      register: uuid

    - set_fact:
        new_uuid: "{{ uuid.stdout }}"

    - name: Claim the node
      command: netdata-claim.sh -token="{{ claim_token }}" -rooms="{{ claim_rooms }}" -url="{{ claim_url }}" -id="{{ new_uuid }}"
      notify: restart netdata agent

  when: not is_claimed
