
---
- name: Ensure unattended-upgrades is installed.
  package: name=unattended-upgrades state=present

- name: Ensure apt-config-auto-update is installed.
  package: name=apt-config-auto-update state=present

- debug:
    msg: "Automatic reboots allowed? {{AutomaticReboot}}"

- debug:
    msg: "MTA? {{mta}}"

- name: Copy unattended-upgrades configuration in place.
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: 0644
  notify: restart unattended-upgrades

- name: Ensure unattended-upgrades is started and enabled on boot.
  service: name=unattended-upgrades state=started enabled=yes
