- hosts: all
  remote_user: "{{ansible_user}}"
  gather_facts: True
  become: yes

  pre_tasks:
    
    - name: Add EPEL repository for Centos/Rocky
      package:
        name: epel-release
        state: latest
        #      when: ansible_facts['os_family'] == 'RedHat'
      when:
        ansible_distribution in ['RedHat', 'CentOS', 'ScientificLinux'] and
        (ansible_distribution_version is version_compare('7', '<') or
        ansible_distribution_version is version_compare('8', '>='))

  roles:
    - { role: install-netdata-repository, become: yes }
    - { role: install-netdata-agent, become: yes }
