---

 - name: Install stable repo
   yum_repository:
     name: netdata-stable
     description: Netdata YUM repo
     #     baseurl: https://packagecloud.io/netdata/netdata-repoconfig/packages/el/7/netdata-repo-1-1.noarch.rpm/download.rpm
     baseurl: https://packagecloud.io/netdata/netdata/el/$releasever/$basearch
     file: Netdata-Stable

 - name: Install edge repo
   yum_repository:
     name: netdata-edge
     description: Netdata YUM repo
     baseurl: https://packagecloud.io/netdata/netdata-repoconfig/packages/el/7/netdata-repo-edge-1-1.noarch.rpm/download.rpm
     file: Netdata-Edge
     enabled: False

     #- name: Install stable repository PGP key
     #  rpm_key:
     #    state: present
     #    key: https://packagecloud.io/netdata/netdata/gpgkey
     #  when: distro == 'stable'

     #- name: Install nightly repository PGP key
     #  rpm_key:
     #    state: present
     #    key: https://packagecloud.io/netdata/netdata-edge/gpgkey
     #  when: distro == 'edge'

     ## I know this is extremely dumb solution but it works
     #- name: Install Netdata stable repository configuration
     #  yum:
     #    name: https://packagecloud.io/netdata/netdata-repoconfig/packages/el/7/netdata-repo-1-1.noarch.rpm/download.rpm
     #    state: present
     #  when: distro == 'stable'

     #- name: Install Netdata nightly repository configuration
     #  yum:
     #    name: https://packagecloud.io/netdata/netdata-repoconfig/packages/el/7/netdata-repo-edge-1-1.noarch.rpm/download.rpm
     #    state: present
     #  when: distro == 'edge'
