---

- name: Install Netdata repo key.
  apt_key:
    url: https://packagecloud.io/netdata/netdata/gpgkey
    state: present

- name: Install Netdata repository package
  apt:
    deb: "{{ repo_uri }}"

