---
- package:
    name: uuid-runtime
    state: latest

- package:
    name: "{{ netdata_agent_package_name }}"
    state: latest
    update_cache: yes

- name: Start "{{ netdata_agent_service_name }}" service
  systemd:
    name: "{{ netdata_agent_service_name }}"
    state: started
    enabled: yes
    masked: no
