---

- package:
    name: "{{ netdata_agent_package }}"
    update_cache: yes
    state: latest

- name: Start "{{ netdata_agent_service }}" service
  systemd:
    name: "{{ netdata_agent_service }}"
    state: started
    enabled: True
