---
# Runs various scheduled automation workflows:
# - .github/scripts/did-nightlies-run.sh -- Whether we last successfully published nightlies
# - .github/scripts/update-website-kickstart-scripts.sh
name: Automation
on:
  schedule:
    - cron: '0 4 * * *'
  pull_request:
jobs:
  did-nightlies-run:
    name: Did Nightlies Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run did-nightlies-run.sh
        env:
          DEBUG: "1"
        run: |
          .github/scripts/did-nightlies-run.sh
      - name: Send Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: '@here Nightlies *NOT* published in last 48hrs'
          SLACK_MESSAGE: |
            The nightlies have not successfully published in the last 48hrs.
            Please check the Travis nightly jobs (marked with `CRON`).
          SLACK_COLOR: '#a30200'
          SLACK_CHANNEL: '#automation'
          SLACK_ICON: 'https://emoji.slack-edge.com/TCC5DL092/netdata/22679c70af359fca.png'
          SLACK_USERNAME: netdatabot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  update-website-kickstart-scripts:
    name: Update Website kickstart* scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.NETDATA_RSA }}
      - name: Append Known Hosts
        run: |
          echo "[138.68.182.52]:2222 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNflFMXwOua2Np1Fywr12HJTpolxxoCIdIC6pArqj1xaIXx6rk76ETzYb23wah2/91r4DRcafPXY5blzHRIZtYo=" >> $HOME/.ssh/known_hosts
      - name: Run .github/scripts/update-website-kickstart-scripts.sh
        run: |
          .github/scripts/update-website-kickstart-scripts.sh
