---
# Runs a script `did-nightlies-run.sh` to determine if we successfully
# published nightly Docker Images, Sources and DEB/RPM packages in the
# last ~48h.
name: Did Nightlies Run?
on:
  schedule:
    - cron: '*/5 * * * *'
  pull_request:
jobs:
  did-nightlies-run:
    name: Did Nightlies Run?
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run did-nightlies-run.sh
        run: |
          .github/did-nightlies-run.sh
