---

- name: remove Netdata packages
  yum:
    state: absent
    name: netdata

- name: Remove the remains
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/netdata
    - /var/log/netdata
    - /var/lib/netdata
    - /var/cache/netdata
    - /usr/libexec/netdata
