---

- name: remove Netdata packages
  dnf:
    state: absent
    name:
      - "{{ netdata_repo_package }}"
      - "{{ netdata_agent_package }}"

- name: Remove the remains
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/netdata
    - /var/log/netdata
    - /var/lib/netdata
    - /var/cache/netdata
    - /usr/libexec/netdata
